SET SCHEMA APP;

create table Department
(   id INTEGER NOT NULL, 
    Name varchar(255),
    PRIMARY KEY(id)
);

create table EmployeePhep
(   id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 100, INCREMENT BY 1), 
    UserId	INTEGER,
    eyear INTEGER, emonth INTEGER, yearmonth INTEGER,
    DateOff datetime, Loai varchar(10),
    DepartmentId int,
	Department varchar(255), Note varchar(255),
    PRIMARY KEY(id)
);

create index EmployeePhep_1 on EmployeePhep(yearmonth, Department, UserId, DateOff);

create table EmployeePhep01
(   id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 100, INCREMENT BY 1), 

    UserId	INTEGER, eyear INTEGER, emonth INTEGER, yearmonthday INTEGER,
    UserCode varchar(20),
    FullName varchar(255),

    DepartmentId int,
    Department varchar(255),

    DateIn Datetime, DateOut Datetime,
	Errorvarchar(255), LoaiPhep varchar(10),
	StartDate DateTime, EndDate Datetime,
    TotTime double, HC double, OT double,
    PRIMARY KEY(id)
);

create index EmployeePhep01_idx on EmployeePhep(yearmonthday, UserId, Department);

