SET SCHEMA APP;

drop table APP.EmployeeDependent;
drop table APP.EmployeeContract;
drop table APP.Employee;

create table Employee
(   id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 100, INCREMENT BY 1), 
    MSNV	varchar(20),
    MSNV6	varchar(20),
    HO	varchar(255),
    TEN	varchar(255),
    DATE_IN     date,
    DATE_OUT	date,
    CHUC_DANH	varchar(255),
    KHOI	varchar(255),
    PHONG_BAN	varchar(255),
    BO_PHAN	varchar(255),
    TOSX    varchar(255),
	CHUC_DANH_THUC	varchar(255),
    TRINH_DO	varchar(255),
    CHUYEN_MON	varchar(255),
    GIOI_TINH	varchar(255),
    TINH_TRANG	varchar(255),
    NGAY_SINH	date,
    NOI_SINH	varchar(255),

    CMND	varchar(20),
    CMND_DATE	date,
    NOI_CAP	varchar(255),

    CMND_01	varchar(20),
    CMND_DATE_01	date,
    NOI_CAP_01	varchar(255),

    DAN_TOC	varchar(255),
    QUOC_TICH	varchar(255),
    NGUYEN_QUAN	varchar(255),
    DIA_CHI_01	varchar(255),
    DIA_CHI_02	varchar(255),
    EMAIL	varchar(255),
    DIEN_THOAI	varchar(255),
    NGUOI_THAN	varchar(255),
    MST	varchar(20),
    MST_NGAY	date,

    ATM	varchar(20),
    ATM_NGAN_HANG	varchar(255),

    ATM_01	varchar(20),
    ATM_NGAN_HANG_01	varchar(255),


    SO_BKXH	varchar(20),
    MA_BENH_VIEN	varchar(20),
    TEN_BENH_VIEN	varchar(255),
    MA_BHYT	varchar(20),
    THAM_GIA_BHXH	date,
    KET_THUC_BHXH	date,
    LUONG_BHXH	double,
    SO_TK_BANK  varchar(20),
    NOTE varchar(255),
    CREATED_DATE date,
	PRIMARY KEY(id)
);
create unique INDEX Employee_MSNV on Employee(MSNV);
create unique INDEX Employee_MSNV6 on Employee(MSNV6);


create table EmployeeDependent
(   id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 100, INCREMENT BY 1), 
    Code VARCHAR(20), 
	Name VARCHAR(255), 
    EmployeeId int not null,
    Active int,
    PRIMARY KEY(id),
    FOREIGN KEY (EmployeeId) REFERENCES Employee(Id)
);
create unique INDEX EmployeeDependent_code on EmployeeDependent(EmployeeId, Code);

create table EmployeeContract
(   id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 100, INCREMENT BY 1), 
    EmployeeId INTEGER not null,
    Code VARCHAR(20), 
    StartDate Date , EndDate Date,
    Note varchar(255),
    ContractType varchar(20),
    primary key (id),
    constraint fk_Employee foreign key (EmployeeId) references Employee(id)
);
create unique INDEX EmployeeContract_code on EmployeeContract(EmployeeId, Code);

/*
select * from Employee
select * from EmployeeDependent
*/