/*
 select * from Document
SELECT * FROM Document WHERE idref=3384 and DocType='contract'
 drop table Document;
 delete from Document;
*/

create table Document
(   id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 100, INCREMENT BY 1), 
	Code varchar(40), -- java.util.UUID.randomUUID()
    FileName VARCHAR(255), 
    DocType varchar(20),
    IdRef  int,
    PRIMARY KEY(id)
);
create unique INDEX Document_code on Document(Code);
create index Document_code_type on Document(DocType, IdRef);

