drop table Users;

CREATE TABLE Users( 
	id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1), 
	uname VARCHAR(60) NOT NULL, 
	password VARCHAR(60) NOT NULL, 
	PRIMARY KEY(id)
);

INSERT INTO Users VALUES(0,'adam','adam');

select * from  Users
